---
name: Sync Readme

on:
  push:
    branches:
      - whale
  schedule:
    - cron: "0 0 * * *" # daily


jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Sync
        uses: ms-jpq/dockerhub-readme
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/dockerhub-readme
          readme: "./README.md"

